services:
  game:
    container_name: game-container
    image: game-image
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 4173:8080
    tty: true
