name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verificar arquivos no diretório atual
        run: ls -la

      - name: Save SSH key
        env:
          ORACLE_SSH_KEY: ${{ secrets.ORACLE_SSH_KEY }}
        run: |
          echo "$ORACLE_SSH_KEY" | tr -d '\r' > /tmp/oracle_key
          chmod 600 /tmp/oracle_key

      - name: Test SSH connection
        env:
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
        run: |
          ssh -i /tmp/oracle_key -o StrictHostKeyChecking=no $ORACLE_USER@$ORACLE_HOST echo "Conexão SSH bem-sucedida"

      - name: Deploy to Oracle server
        env:
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
        run: ssh -i /tmp/oracle_key $ORACLE_USER@$ORACLE_HOST 'bash -s' < ./deploy.sh
