name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar arquivos no diret√≥rio atual
        run: ls -la

      - name: Deploy to Oracle server
        env:
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
          ORACLE_SSH_KEY: ${{ secrets.ORACLE_SSH_KEY }}
        run: |
          ssh -i $ORACLE_SSH_KEY $ORACLE_USER@$ORACLE_HOST 'bash -s' < ./deploy.sh
